[package]
name = "leetcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p149"
path = "src/p149.rs"

[[bin]]
name = "p232"
path = "src/p232.rs"

[[bin]]
name = "p441"
path = "src/p441.rs"

[[bin]]
name = "p705"
path = "src/p705.rs"

[[bin]]
name = "p2148"
path = "src/p2148.rs"