[package]
name = "update"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = "4.5.48"
toml_edit = "0.23.6"
notify = "8.2.0"
ctrlc = "3.5.0"

[[bin]]
name = "update"
path = "main.rs"
