// This file is automatically generated by the update_modules script.
// Do not edit manually - your changes will be overwritten.

#[path = "solutions/count-prime-gap-balanced-subarrays.rs"]
mod count_prime_gap_balanced_subarrays;

#[path = "solutions/count-special-triplets.rs"]
mod count_special_triplets;

#[path = "solutions/find-maximum-area-of-a-triangle.rs"]
mod find_maximum_area_of_a_triangle;

#[path = "solutions/find-weighted-median-node-in-tree.rs"]
mod find_weighted_median_node_in_tree;

#[path = "solutions/generate-tag-for-video-caption.rs"]
mod generate_tag_for_video_caption;

#[path = "solutions/max-difference-you-can-get-from-changing-an-integer.rs"]
mod max_difference_you_can_get_from_changing_an_integer;

#[path = "solutions/maximum-difference-between-increasing-elements.rs"]
mod maximum_difference_between_increasing_elements;

#[path = "solutions/maximum-product-of-first-and-last-elements-of-a-subsequence.rs"]
mod maximum_product_of_first_and_last_elements_of_a_subsequence;

#[path = "solutions/minimize-the-maximum-difference-of-pairs.rs"]
mod minimize_the_maximum_difference_of_pairs;

#[path = "solutions/minimum-adjacent-swaps-to-alternate-parity.rs"]
mod minimum_adjacent_swaps_to_alternate_parity;

#[path = "solutions/minimum-deletions-to-make-string-k-special.rs"]
mod minimum_deletions_to_make_string_k_special;

#[path = "solutions/minimum-steps-to-convert-string-with-operations.rs"]
mod minimum_steps_to_convert_string_with_operations;

#[path = "solutions/two-sum.rs"]
mod two_sum;

